import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { PassportReader } from "@gitcoinco/passport-sdk-reader";
let verifier
import("@gitcoinco/passport-sdk-verifier").then(ver => verifier = new ver.PassportVerifier());
let scorer
import('@gitcoinco/passport-sdk-scorer').then(sco => scorer = sco);
import { useEffect, useState } from "react";
import { useAccount } from "wagmi";

// https://ceramic.staging.dpopp.gitcoin.co/
// https://ceramic-clay.3boxlabs.com
const reader = new PassportReader("https://ceramic-clay.3boxlabs.com", "1");

const Home: NextPage = () => {
  const [address, setAddress] = useState("");
  const [score, setScore] = useState(0)
  const { data } = useAccount();

  useEffect(() => {
    if (data && data.address !== undefined) {
      setAddress(data.address);
    }
  }, []);

  useEffect(() => {
    async function a() {
      console.log("address: ", address);
      const passport = await reader.getPassport(address);
      console.log("passport: ", passport);
      console.log('verifier', verifier)
      const verified = await verifier.verifyPassport(address, passport);
      console.log('verified: ', verified)
      const scorerI = new scorer.PassportScorer([
        {
            provider: 'Ens',
            issuer: 'did:key:z6MkghvGHLobLEdj1bgRLhS4LPGJAvbMA1tn2zcRyqmYU5LC',
            score: 1
        },
        {
            provider: 'Twitter',
            issuer: 'did:key:z6MkghvGHLobLEdj1bgRLhS4LPGJAvbMA1tn2zcRyqmYU5LC',
            score: 0.5
        },
        {
          provider: 'Google',
          issue: 'did:key:z6MkghvGHLobLEdj1bgRLhS4LPGJAvbMA1tn2zcRyqmYU5LC',
          score: 1
        }
    ], 'https://ceramic.passport-iam.gitcoin.co', '1');
    const score = await scorerI.getScore(address, passport);
    console.log('score: ', score)
    setScore(score)
    }
    if (address !== "" && address !== undefined) {
      a();
    }
  }, [address]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Passport Checker</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>Welcome to PassportChecker!</h1>
        {
          score >= 1.5 ?
          <div>You have a high enough score to enter!</div>
          :
          <div>Sorry score is too low.</div>
        }
      </main>
    </div>
  );
};

export default Home;
